version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
    networks:
      - hireo_job_network
    volumes:
      - hireo_job_volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest  
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000   
    networks:
      - hireo_job_network
    container_name: zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
    networks:
      - hireo_job_network
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
      - "9093:9093"
      
  api-gateway:
    build: ./api-gateway/
    restart: always
    container_name: api-gateway
    networks:
      - hireo_job_network
    ports:
      - "8000:8000"

  auth-services:
    build: ./auth-service/
    restart: always
    depends_on:
      - postgres
    container_name: auth-service
    networks:
      - hireo_job_network
    hostname: auth-service

  job-service:
    build: ./job-service/
    depends_on:
      - postgres
      - kafka
    restart: always
    container_name: job-service
    networks:
      - hireo_job_network
    hostname: job-service

networks:
  hireo_job_network:
    driver: bridge

volumes:
  hireo_job_volume:
