apiVersion: apps/v1
kind: Deployment
metadata:
  name: hireo_job-job-svc
  namespace: hireo_job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job_service
  template:
    metadata:
      labels: 
        app: job_service
    spec:
      containers:
      - image: rahulchacko/hireo_job-job-service
        name: job-svc-container
        ports:
        - containerPort: 50052
        resources:
          limits:
            cpu: ".2"
            memory: "250Mi"
          requests:
            cpu: ".1"
            memory: "150Mi"
        

---

apiVersion: v1
kind: Service
metadata:
  namespace: hireo_job
  name: hireo_job-job-service
spec:
  type: ClusterIP
  ports:
  - port: 50052
    targetPort: 50052
  selector:
    app: job_service