apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-deployment
  namespace: hireo_job
spec:
  replicas: 1
  selector:
    matchLabels:
      database: mongodb
  template:
    metadata:
      name: mongodb-pod
      labels:
        database: mongodb
    spec:
      containers:
      - image: mongo
        name: hireo_job-mongodb-container
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongostorage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongostorage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Mi
        # limits:
        #   storage: 20Mi


---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: hireo_job
spec:
  selector:
    database: mongodb
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017